pub mod api;
pub mod auth;
pub mod cli;
pub mod config;
pub mod control_plane;
pub mod crypto;
pub mod deploy;
pub mod filter;
pub mod health;
pub mod model;
pub mod process;
pub mod provisioning;
pub mod scheduler;
pub mod session;
pub mod singbox_adapter;
pub mod state;
mod state_model;
pub mod supervisor;
mod supervisor_render;
pub mod template;

pub use api::{CertificateRequest, CertificateResponse, ProtonApiClient};
pub use auth::{SrpProof, calculate_srp_proof, resolve_two_factor_code};
pub use control_plane::{CertificateRefreshOutcome, ControlPlane, ControlPlaneConfig};
pub use crypto::{KeyMaterial, generate_key_material};
pub use deploy::{DeployPlan, deploy_with_sighup};
pub use filter::{FeatureMask, ServerFilter, select_target};
pub use health::{HealthMonitor, HealthStatus, ProbeResult};
pub use model::{LogicalServer, PhysicalServer};
pub use process::{find_process_pid, find_process_pid_by_exe, sighup_process};
pub use provisioning::{LocalKeyProvisioner, WireGuardCredentials, WireGuardProvisioner};
pub use scheduler::{RefreshDecision, RefreshScheduler};
pub use session::{ActiveOutbound, SessionStore, UserSession};
pub use singbox_adapter::{SingboxWireGuardEndpoint, build_wireguard_endpoint};
pub use template::hydrate_template;
